# Generated by Django 4.2.6 on 2023-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', null=True)),
                ('email', models.CharField(default='', max_length=2000)),
                ('subject', models.CharField(default='', max_length=1000)),
                ('topic', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
