# Generated by Django 4.2.6 on 2023-10-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='topic',
            new_name='phone',
        ),
    ]
